app/snipe/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort, session
from .models import Url, User
from .utils import db, bcrypt, limiter, cache, login_manager, mail
from app.helpers.view import URLCreator
from flask_caching import Cache
from flask_limiter import Limiter
from sqlalchemy import desc
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from flask_share import Share
from flask_mail import Message
from datetime import timedelta


auth = Blueprint('auth', __name__)


@login_manager.user_loader
def user_loader(id):
    return User.query.get(int(id))


from werkzeug.security import generate_password_hash, check_password_hash

@auth.route("/signup", methods=['GET', 'POST'])
@limiter.limit("2 per minute")
def signup():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        phone_number = request.form.get('phone_number')
        password = request.form.get('password')
        password_confirmation = request.form.get('password_confirmation')
      
        if password != password_confirmation:
            flash("Password confirmation does not match", category="error")
            return redirect(url_for('auth.signup'))
     
        if len(password) < 8 or not any(c in "!@#$%^&*(),.?\":{}|<>1234567890" for c in password):
            flash("Password must be at least 8 characters long and contain a special character or number", category="error")
            return redirect(url_for('auth.signup'))

        email_exists = User.query.filter_by(email=email).first()
        if email_exists:
            flash("Email already registered", category="error")
            return redirect(url_for('auth.signup'))

        phone_number_exists = User.query.filter_by(phone_number=phone_number).first()
        if phone_number_exists:
            flash("Phone number already registered", category="error")
            return redirect(url_for('auth.signup'))
        
        password_hash = generate_password_hash(password)

        new_user = User(name = name,
                        phone_number = phone_number,
                        email = email, 
                        password = password_hash)
        flash("Account created")
        new_user.save()

        return redirect(url_for('auth.login'))

    return render_template('signup.html')




@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if not user:
            flash("User does not exist", category="error")
            
        elif check_password_hash(user.password, password):
            flash(f'Success!! Welcome {email}')
            login_user(user)

            session.permanent = True

            return redirect(url_for('snipe.home'))
        
        else:
            flash("Credentials do not match", category="error")

    return render_template('signin.html')



    
    

@auth.route('/protected')
@login_required
def protected():
    
    return render_template('protected.html', email=current_user)


@auth.route('/logout', methods=['GET', 'POST'])
def logout():
    
    flash('Goodbye')
    logout_user()

    return redirect(url_for('snipe.index'))



@auth.route("/change_password", methods=['GET', 'POST'])
@login_required
def change_password():
    if request.method == 'POST':
        current_password = request.form.get('current_password')
        new_password = request.form.get('new_password')
        confirm_password = request.form.get('confirm_password')

        if not check_password_hash(current_user.password, current_password):
            flash("Incorrect current password", category="error")
            return redirect(url_for('auth.change_password'))

        if new_password != confirm_password:
            flash("Password confirmation does not match", category="error")
            return redirect(url_for('auth.change_password'))

        if len(new_password) < 8 or not any(c in "!@#$%^&*(),.?\":{}|<>1234567890" for c in new_password):
            flash("New password must be at least 8 characters long and contain a special character or number", category="error")
            return redirect(url_for('auth.change_password'))

        if check_password_hash(current_user.password, new_password):
            flash("New password must be different from the current password", category="error")
            return redirect(url_for('auth.change_password'))

        current_user.password = generate_password_hash(new_password)
        current_user.save()

        flash("Password changed successfully")
        return redirect(url_for('auth.profile'))

    return render_template('password_change.html')







@auth.route('/<int:user_id>/profile/', methods=["GET", "POST"])
@login_required
def profile(user_id):

    user = User.query.filter_by(id=current_user.id).first()
    
    page = request.args.get('page', 1, type=int)
    per_page = 5 

    urls = Url.query.filter_by(user_id=current_user.email).order_by(desc(Url.date_created)).paginate(page=page, per_page=per_page)
    
    context = {
    'user': user.name,
    'email': user.email,
    'phone_number': user.phone_number,
    'date': user.created_at,
    'urls': urls,
    'new_url': request.args.get('new_url'),
    'custom_url_created': request.args.get('custom_url_created'),
    }

    
    return render_template('profile.html', **context)


# @auth.route('/forgot_password', methods=['GET', 'POST'])
# def forgot_password():
#     if request.method == 'POST':
#         email = request.form['email']
#         user = User.query.filter_by(email=email.lower()).first()
#         link = request.host_url + "reset_password/" + email
#         if user:
#             try:
#                 msg = Message('Reset Password', sender="admin@redr.site", recipients=[email])
#                 msg.html = render_template('reset_mail.html', link=link)
#                 mail.send(msg)
#             except:
#                 flash ("Reset password failed. Please try again.")
#                 return redirect(url_for('login'))
#             flash('Reset password link sent successfully. Please check your mail inbox or spam.')
#             return redirect(url_for('login'))
#         flash('Email not found.')
#         return redirect(url_for('forgot_password'))
#     return render_template('forgot_password.html')




# @auth.route('/reset_password/<email>', methods=['GET', 'POST'])
# def reset_password(email):
#     user = User.query.filter_by(email=email).first()
#     if user:
#         if request.method == 'POST':
#             password = request.form['password']
#             confirm_password = request.form['confirm_password']
#             if password == confirm_password:
#                 user.password = generate_password_hash(password, method='sha256')
#                 db.session.commit()
#                 flash('Password reset successfully. Please login.')
#                 return redirect(url_for('login'))
#             else:
#                 flash('Passwords do not match. Please try again.')
#                 return redirect(url_for('reset_password', email=email))
#         return render_template('reset_password.html', email=email)
#     return 'Email not found.'

app/snipe/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file, jsonify, abort
from .models import Url, Country, User
from .utils import db, bcrypt, limiter, cache, login_manager
from sqlalchemy import desc
from app.helpers.view import URLCreator, generate_qr_code
from flask_caching import Cache
from flask_jwt_extended import get_jwt_identity
from flask_limiter.util import get_remote_address
from flask_login import login_required, current_user
import qrcode
import io
import base64


snipe = Blueprint('snipe', __name__)



@snipe.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('snipe.home'))
    else:
        return render_template('frontIndex.html')


@snipe.route('/home')
@login_required
def home():
    
    page = request.args.get('page', 1, type=int)
    per_page = 5 

    urls = Url.query.filter_by(user_id=current_user.email).order_by(desc(Url.date_created)).paginate(page=page, per_page=per_page)
    new_url = request.args.get('new_url')
    custom_url_created = request.args.get('custom_url_created')
    context = {
        'urls': urls,
        'new_url': new_url,
        'custom_url_created': custom_url_created
        }

    return render_template('home.html', **context)


@snipe.route('/create', methods=['POST', 'GET'])
@limiter.limit("5 per minute")
@login_required
def create():
    if request.method == 'POST':
        url = request.form.get('url')

        existing_url = Url.query.filter_by(url=url, user_id=current_user.email).first()
        if existing_url:
            flash("Short URL already exists", category="error")
            return redirect(url_for('snipe.home'))

        if URLCreator.is_valid_url(url):
            url_title = URLCreator.extract_url_data(url)
            short_url = URLCreator.short_url(url)

            new_url = Url(
                url=url,
                url_title=url_title,
                short_url=short_url,
                user_id=current_user.email
            )

            try:
                new_url.save()
                flash("Success! Short URL created")
            except:
                db.session.rollback()
                return render_template('error.html')
            

        return redirect(url_for('snipe.home', new_url=short_url))
        



@snipe.route('/<random_string_combination>')
def redirect_to_original(random_string_combination):
    short_url = f"http://{request.host}/{random_string_combination}"
    url = Url.query.filter_by(short_url=short_url).first()
    if url:
        url.clicks += 1
        url.save()
        return redirect(url.url)
    else:
        abort(404)



@snipe.route('/custom', methods=['POST', 'GET'])
@limiter.limit("5 per minute")
@login_required
def custom():
    if request.method == 'POST':
        url = request.form.get('url')
        custom_url_entry = request.form.get('custom_url_entry')
        custom_url = None  # Assign a default value to custom_url

        existing_url = Url.query.filter_by(custom_url=custom_url_entry, user_id=current_user.email).first()
        if existing_url:
            flash("Custom URL already exists", category="error")
            return redirect(url_for('snipe.home'))

        if URLCreator.is_valid_url(url):
            url_title = URLCreator.extract_url_data(url)
            custom_url = f"http://{request.host}/{custom_url_entry}"

            custom_url_created = Url(
                url=url,
                url_title=url_title,
                short_url=custom_url,
                user_id=current_user.email
            )

            try:
                custom_url_created.save()
                flash("Success! Custom URL created")
            except:
                db.session.rollback()
                return render_template('error.html')

        return redirect(url_for('snipe.home', custom_url_created=custom_url))




@snipe.route('/<int:id>/view/', methods=["GET", "POST"])
@limiter.limit("5 per minute")
@cache.cached(timeout=30)
@login_required
def view(id):

    url = Url.get_by_id(id)
    return render_template('view.html', url=url)



@snipe.route('/<int:id>/delete', methods=['POST', 'GET', 'DELETE'])
@limiter.limit("5 per minute")
@cache.cached(timeout=30)
@login_required
def delete_url(id):
    
    url = Url.get_by_id(id)
    if url:
        db.session.delete(url)
        db.session.commit()
        flash("URL successfully deleted")
        
    return redirect(url_for('auth.profile', user_id=current_user.id))
    



@snipe.route('/<int:id>/qrcode/', methods=['POST', 'GET'])
@login_required
@limiter.limit("5 per minute")
def generate_qr_code_url(id):
    url = Url.get_by_id(id)
    
    if url:
        img = qrcode.make(url.url)
        img_io = io.BytesIO()
        img.save(img_io, 'PNG')
        img_io.seek(0)
        
        qr_code_data = base64.b64encode(img_io.getvalue()).decode('utf-8')
        
        url.qr_code_url = qr_code_data
        url.save()
        
        return send_file(img_io, mimetype='image/png')
    
    return 'URL not found.', 404



@snipe.route('/save_country', methods=['POST'])
@login_required
def save_country():
    url_id = request.form.get('url_id')
    country_name = request.form.get('country_name')
    clicks = request.form.get('clicks')

    url = Url.get_by_id(url_id)
    if url:
        country = Country(country=country_name, clicks=clicks, url_id=url_id)
        country.save()
        return jsonify({'message': 'Country saved successfully.'})
    else:
        return jsonify({'error': 'URL not found.'}), 404



@snipe.route('/about', methods=['GET'])
@login_required
@limiter.limit("5 per minute")
@cache.cached(timeout=59)
def about():
    
    return render_template('about.html')


@snipe.route('/<int:user_id>/edit/', methods=['PATCH', 'PUT', 'GET', 'POST'])
@login_required
@limiter.limit("1 per week")
def edit(user_id):
    
    profile = User.query.filter_by(email=current_user.email).first()

    if request.method == 'POST':
        profile.name = request.form['name']
        profile.email = request.form['email']
        profile.phone_number = request.form['phone_number']
    
        db.session.commit()
        flash("Success! Profile updated")
        return redirect(url_for('auth.profile', user_id=current_user.id))
    
    return render_template('edit.html')

app/snipe/templates/about.html
{% extends 'base.html' %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css')}}">

{% block head %}
  <title>About</title>
{% endblock %}

{% block body %}

<section class="top-nav">
  <div>
    Snip
  </div>
  <input id="menu-toggle" type="checkbox" />
  <label class='menu-button-container' for="menu-toggle">
  <div class='menu-button'></div>
</label>
  <ul class="menu">
    {% if current_user.is_authenticated %}
              <li><a href="{{url_for('auth.profile', user_id=current_user.id)}}">Profile</a></li>
              <li><a href="{{ url_for('snipe.home') }}">Home</a></li>
              <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% else %}
              <li><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
              <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            {% endif %}
  </ul>
</section>


<center>
    <div class="profile-image">
      <img src="../static/images/00100sPORTRAIT_00100_BURST20181005110856440_COVER~2.jpg" alt="Profile Image">
    </div>
  </center>

<center>
  <div class="my-info">
    <p class="intro">My name is Victor Iyayi. I'm a Junior Backend Engineer with 2 years of experience.<br>I'm open to more roles, to expand my knowledge.</p>
    <p class="contact-info">Email - veektaw@gmail.com or Iyayi.ose.victor@gmail.com<br>Phone - 0706 345 8587</p>
  </div>
</center>
  

{% endblock %}

app/snipe/templates/edit.html
{% extends 'base.html' %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css')}}">

{% block head %}
  <title>Edit</title>
{% endblock %}

{% block body %}



<section class="top-nav">
    <div>
      Snip
    </div>
    <input id="menu-toggle" type="checkbox" />
    <label class='menu-button-container' for="menu-toggle">
      <div class='menu-button'></div>
    </label>
    <ul class="menu">
      {% if current_user.is_authenticated %}
            <li><a href="{{url_for('auth.profile', user_id=current_user.id)}}">Profile</a></li>
            <li><a href="{{ url_for('snipe.home') }}">Home</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      {% else %}
        <li><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
      {% endif %}
    </ul>
</section>
<center>
    <div style="margin-top: 200px;">
        <h1 style="margin-right: auto; margin-left: auto; margin-bottom: 10px; margin-top: 70px; color: #2b5cd8; font-size: 30px;">Edit your profile</h1>
        <form action="{{ url_for('snipe.edit', user_id=current_user.id) }}" method="POST" class="form">
            <input style="width: 70%; margin-bottom: 30px;"  type="text" placeholder="Your name" name="name" required>
            <input style="width: 70%; margin-bottom: 30px;"  type="text" placeholder="Your email" name="email" required>
            <input style="width: 70%; margin-bottom: 30px;"  type="text" placeholder="Your phone number" name="phone_number" required>
            <button type="submit" value="Update" style="width: 100px; height: 40px; background-color: #2b5cd8; border-radius: 4px; color: aliceblue; display: block;">Update</button>
        </form>
    </div>
</center>


{% endblock %}

app/snipe/templates/home.html
{% extends 'base.html' %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css')}}">

{% block head %}
  <title>Home</title>
{% endblock %}

{% block body %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% set error_displayed = false %}
    {% for message in messages %}
      {% if 'error' in message.lower() and not error_displayed %}
        {% set error_displayed = true %}
        <div role="alert" class="alert error">
          <p class="alert-msg">{{ message }}</p>
        </div>
      {% elif 'error' not in message.lower() %}
        <div role="alert" class="alert normal">
          <p class="alert-msg">{{ message }}</p>
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}
{% endwith %}

<section class="top-nav">
  <div>
    Snip
  </div>
  <input id="menu-toggle" type="checkbox" />
  <label class='menu-button-container' for="menu-toggle">
  <div class='menu-button'></div>
</label>
  <ul class="menu">
    {% if current_user.is_authenticated %}
                <li><a href="{{ current_user.id }}/profile/">Profile</a></li>
                <li><a href="{{ url_for('snipe.about') }}">About</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% else %}
                <li><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            {% endif %}
  </ul>
</section>




<div class="top-layer1">
  <h1 class="description">Create short URL</h1>
  <form action="{{ url_for('snipe.create') }}" method="POST">
    <center>
      <input type="text" class="text-field-content-row" name="url" placeholder="Enter your long URL here . . ." id="input-field" required/>
    </center>
    <div class="top-buttons">
      <center>
        <button type="submit" id="shorten" class="content-row button">Shorten URL</button>
        <button type="button" id="clear-btn" class="content-row button">Clear</button>
      </center>
    </div>
  </form>

  <!-- Output and copy -->
  <div id="output-div">
    <div class="content-row" id="new-url-label">Your short URL - <p class="new-url-result">{{new_url}}</p></div>
    <div class="copy-div">
      <button type="button" id="copy-btn" class="copy-btn3" data-clipboard-target="#new-url">Copy</button>
    </div>
  </div>
  <div id="error-div">
    <p class="content-row" id="error-text"></p>
  </div>
</div>

<div class="top-layer2">
  <h1 class="description">Create custom URL</h1>
  <form action="{{ url_for('snipe.custom') }}" method="POST" class="form2">
    <input type="text" class="text-field-content-row2" name="long_url" placeholder="Enter your long URL here . . ." id="input-field" required/>
    <input type="text" class="text-field-content-row2" name="custom_url_entry" placeholder="Enter your custom URL here . . ." id="custom-input-field" required style="margin-bottom: 0px;"/>
    <center>
      <button type="submit" id="shorten" class="content-row button">Custom URL</button>
      <button type="button" id="clear-btn2" class="content-row button">Clear</button>
    </center>
  </form>

  <!-- Output and copy -->
  <div id="output-div">
    <div class="content-row" id="custom-url-label">Your custom URL - <p class="custom-url-result" id="custom-url-created">{{custom_url_created}}</p></div>
    <div class="copy-div">
      <button type="button" id="copy-btn1" class="copy-btn4" data-clipboard-target="#custom-url-created" class="content-row button">Copy</button>
    </div>
  </div>
  <div class="" id="error-div">
    <p class="content-row" id="error-text"></p>
  </div>
</div>






<!-- App script -->
<script src="{{ url_for('static', filename='js/app.js') }}"></script>
<script src="{{ url_for('static', filename='js/engage.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>

{% endblock %}

app/snipe/templates/profile.html
{% extends 'base.html' %}



{% block head %}
  <title>Profile</title>
{% endblock %}

{% block body %}

{% with messages = get_flashed_messages() %}
{% if messages %}
    {% set error_displayed = false %}
        {% for message in messages %}
            {% if 'error' in message.lower() and not error_displayed %}
                {% set error_displayed = true %}
                    <div role="alert" class="alert error">
                        <p class="alert-msg">{{ message }}</p>
                    </div>
                {% elif 'error' not in message.lower() %}
                    <div role="alert" class="alert normal">
                        <p class="alert-msg">{{ message }}</p>
                    </div>
            {% endif %}
    {% endfor %}
{% endif %}
{% endwith %}



<section class="top-nav">
    <div>
      Snip
    </div>
    <input id="menu-toggle" type="checkbox" />
    <label class='menu-button-container' for="menu-toggle">
      <div class='menu-button'></div>
    </label>
    <ul class="menu">
      {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('snipe.home') }}">Home</a></li>
        <li><a href="{{ url_for('snipe.about') }}">About</a></li>
        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      {% else %}
        <li><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
      {% endif %}
    </ul>
</section>

<div class="main">
    <h2 style="margin-right: 91.5%; color: #043c8c">Your Profile</h2>
    <div class="card-profile">
      <div class="card-body" style="text-align: left;">
        <i class="fa fa-pen fa-xs edit"></i>
        <div class="column">
          <div class="profile-actions">
            <i class="material-icons settings-icon" style="margin-top: 7.5px; color: #2b5cd8;">settings</i>
            <a href="{{ url_for('snipe.edit', user_id=current_user.id) }}" class="qrcode_create" style="margin-bottom: 20px;">
              <p class="qrcode_click">Edit profile</p>
            </a>
  
            <a href="{{ url_for('auth.change_password')}}" class="qrcode_create" style="margin-bottom: 20px;">
              <p class="qrcode_click">Change password</p>
            </a>
          </div>
  
          <p class="profile-info"><i class="material-icons">person</i><span id="user-name" style="font-weight: bolder;">{{ current_user.name }}</span></p>
          <p class="profile-info"><i class="material-icons">email</i><span id="user-email" style="font-weight: bolder;">{{ current_user.email }}</span></p>
          <p class="profile-info"><i class="material-icons">phone</i><span id="user-phone" style="font-weight: bolder;">{{ current_user.phone_number }}</span></p>
        </div>
      </div>
    </div>
  </div>
  

  

    <h2 style="margin-top: 100px;">Your URL history</h2>
    <section class="hero" style="padding: 30px 20px;">
      
      {% if current_user.is_authenticated %}
        {% if urls %}
          {% for url in urls.items %}
            {% if url.user_id == current_user.email %}
              <div class="card">
                <a href="/{{ url.id }}/view/" style="color: black; text-decoration: none;">
                  <h1 class="card-text" style="color: black; text-decoration: none; font-size: 70%; word-wrap:break-word;">{{ url.url_title }}</h1>
                </a>
                <h5 class="date_created">{{ url.date_created.strftime('%B %d, %Y') }}</h5>
                <h5 class="card-title" style="font-weight: lighter;">
                  <div class="engagements">
                    <p class="engagement-clicks" id="engagement-{{ url.id }}" style="font-weight: lighter;">{{ url.clicks }}</p>
                  </div>
                  Total engagements
                </h5>

                {% if url.custom_url %}
                  <a href="{{ url.url }}" class="url-link" id="url_click{{ url.id }}" style="color: #ff7518; font-size: 55%; margin-top: 5px; font-weight: lighter;">
                    <p class="short-url-history" id="copy-target-{{ url.id }}" style="font-weight: lighter;">{{ url.custom_url }}</p>
                  </a>
                {% else %}
                  <a href="{{ url.url }}" class="url-link" id="url_click{{ url.id }}" style="color: #ff7518; font-size: 55%; margin-top: 5px; font-weight: lighter;">
                    <p class="short-url-history" id="copy-target-{{ url.id }}" style="font-weight: lighter;">{{ url.short_url }}</p>
                  </a>
                {% endif %}

                <button type="button" class="copy-btn5" data-clipboard-target="#copy-target-{{ url.id }}">Copy</button>

                <form action="{{ url_for('snipe.delete_url', id=url.id) }}" method="POST" class="form-profile">
                  <button type="submit" id="delete-btn" class="delete-btn2">Delete</button>
                </form>

                <a href="{{ url_for('snipe.generate_qr_code_url', id=url.id) }}" class="qrcode_create"><p class="qrcode_click">Create QR code</p></a>
              </div>
            {% endif %}
          {% endfor %}

          <div class="pagination-container">
            {% if urls.has_prev %}
              <div class="page-num1">
                <a href="{{ url_for('auth.profile', user_id=current_user.id, page=urls.prev_num) }}" class="pagination-link">&lt; Previous</a>
              </div>
            {% endif %}
          
            <div class="pagination-numbers">
              {% for num in urls.iter_pages() %}
                {% if num %}
                  {% if num == urls.page %}
                    <div class="page-num1 current-page">
                      <span class="pagination-link">{{ num }}</span>
                    </div>
                  {% else %}
                    <div class="page-num1">
                      <a href="{{ url_for('auth.profile', user_id=current_user.id, page=num) }}" class="pagination-link">{{ num }}</a>
                    </div>
                  {% endif %}
                {% endif %}
              {% endfor %}
            </div>
          
            {% if urls.has_next %}
              <div class="page-num1">
                <a href="{{ url_for('auth.profile', user_id=current_user.id, page=urls.next_num) }}" class="pagination-link">Next &gt;</a>
              </div>
            {% endif %}
          </div>

        {% endif %}
      {% endif %}

    </section>

<script src="{{ url_for('static', filename='js/copy_profile.js') }}"></script>
<script src="{{ url_for('static', filename='js/engage.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>

{% endblock %}

app/snipe/templates/protected.html
{% extends 'home.html' %}
{% block content %}

    <h1>This is a Protected Route</h1>
{% endblock content %}

app/snipe/templates/view.html
{% extends 'base.html' %}

{% block head %}
  <title>View</title>
{% endblock %}

{% block body %}

<section class="top-nav">
    <div>
      Snip
    </div>
    <input id="menu-toggle" type="checkbox" />
    <label class='menu-button-container' for="menu-toggle">
    <div class='menu-button'></div>
  </label>
    <ul class="menu">
      {% if current_user.is_authenticated %}
                <li><a href="{{url_for('auth.profile', user_id=current_user.id)}}">Profile</a></li>
                <li><a href="{{ url_for('snipe.about') }}">About</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
              {% else %}
                <li><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
              {% endif %}
    </ul>
  </section>

        
    <section class="hero" style="padding: 0px 20px;">
        <center>
          
          <h1 class="description2" style="margin-top: 170px;">Your URL</h1>
        </center>
        {% if current_user.is_authenticated %}
        {% if url %}
          {% if url.user_id == current_user.email %}
          <div class="card" style="border-bottom: 0px; box-shadow: 1px 1px 8px 0 grey; border-radius: 18px;">
            
            <a href="{{ url.url }}" style="color: black; text-decoration: none;" >
                <h1 class="card-text" style="color: black; text-decoration: none; font-size: 26px;">{{ url.url_title }}</h1>
            </a>
            <h5 style="color: #2b5cd8; font-size: 15px; font-weight: lighter; margin-bottom: 4px; width: 50%; word-wrap:break-word;"><strong style="color: #1b1b1b;">Long URL</strong> - {{url.url}}</h5>
            
            <h5 class="date_created">{{ url.date_created.strftime('%B %d, %Y') }}</h5>
            <h5 class="card-title"  style="font-weight: lighter;">
              <div class="engagements">
                <p class="engagement-clicks" id="engagement-{{ url.id }}" style="font-weight: lighter;">{{ url.clicks }}</p>
              </div>
              Total engagements
            </h5>

            <h5 class="card-title" style="font-weight: lighter; margin-top: 3px;">
                List of countries:
                <ul id="country-list">
                  {% for country in url.country %}
                    <li>{{ country.country }} - Clicks: {{ country.clicks }}</li>
                  {% endfor %}
                </ul>
            </h5>
              

            
            {% if url.custom_url %}
                <a href="{{ url.url }}" class="url-link" id="url_click{{ url.id }}" style="color: #ff7518; font-size: 55%; margin-top: 5px; font-weight: lighter;">
                <p class="short-url-history" style="font-weight: lighter;">{{ url.custom_url }}</a></p>
            {% else %}

                <a href="{{ url.url }}" class="url-link" id="url_click{{ url.id }}" style="color: #ff7518; font-size: 55%; margin-top: 5px; font-weight: lighter;">
                <p class="short-url-history" style="font-weight: lighter;">{{ url.short_url }}</a></p>
            {% endif %}
            <button id="copy-btn" class="copy-btn2" data-clipboard-target="#new_url">Copy</button>
                <a href="/{{ url.id }}/delete"><button id="delete-btn" class="delete-btn2">Delete</button></a>
                <a href="{{ url_for('snipe.generate_qr_code_url', id=url.id) }}" class="qrcode_create"><p class="qrcode_click">Create QR code</p></a>
                

          {% endif %}
        {% endif %}
        {% endif %}
    </section>
             <!--App script-->
             <script src="{{url_for('static', filename='js/copy.js')}}"></script>
             <script src="{{url_for('static', filename='js/engage.js')}}"></script>
             <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>
        
{% endblock %}